In [2]:
a=[3,56,79,10,0]
a.sort()
print(a)

[0, 3, 10, 56, 79]


In [5]:
a=[2,45,67,87]
b=sorted(a)
print(b)

[2, 45, 67, 87]


In [8]:
a=(1,25500,36,45,98)
b=sorted(a)
print(a)
print(b)

(1, 25500, 36, 45, 98)
[1, 36, 45, 98, 25500]


In [11]:

#reshape-converting into 2d array
A=np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [1]:
import numpy as np

In [16]:
A=np.linspace(1,13,12).reshape(4,3)
print(A)


[[ 1.          2.09090909  3.18181818]
 [ 4.27272727  5.36363636  6.45454545]
 [ 7.54545455  8.63636364  9.72727273]
 [10.81818182 11.90909091 13.        ]]


In [18]:
A=np.array([2,45,67,90,12,34,56,12]).reshape(2,2,2)
print(A)

[[[ 2 45]
  [67 90]]

 [[12 34]
  [56 12]]]


In [24]:
#Array creation and subtraction
A=np.array([34,23,56,45])
B=np.array([24,56,78,90])
C=A-B
print(C)

[ 10 -33 -22 -45]


In [22]:
B=np.array([2,45,67,90,12,34,56,12])
B.resize(2,2,2)#changes the shape of original array
#reshape needs changes save in another variable
print(B)

[[[ 2 45]
  [67 90]]

 [[12 34]
  [56 12]]]


In [25]:
A=np.array([12,13,14,15])
B=np.array([23,56,78,10])
c=A+B
print(C)

[ 10 -33 -22 -45]


In [35]:
A=np.array([12,13,14,15]).reshape(2,2)
B=np.array([23,56,78,10]).reshape(2,2)
print(A)
print("----------")
print(B)
print("----------")
C=A*B#Matrix multiplication
print(C)


[[12 13]
 [14 15]]
----------
[[23 56]
 [78 10]]
----------
[[ 276  728]
 [1092  150]]


In [36]:
A=np.array([12,13,14,15]).reshape(2,2)
B=np.array([23,56,78,10]).reshape(2,2)
print(A)
print("----------")
print(B)
print("----------")
C=A@B#Matrix multiplication
print(C)

[[12 13]
 [14 15]]
----------
[[23 56]
 [78 10]]
----------
[[1290  802]
 [1492  934]]


In [37]:
A=np.array([12,13,14,15]).reshape(2,2)
B=np.array([23,56,78,10]).reshape(2,2)
print(A)
print("----------")
print(B)
print("----------")
C=A.dot(B)#Matrix multiplication
print(C)

[[12 13]
 [14 15]]
----------
[[23 56]
 [78 10]]
----------
[[1290  802]
 [1492  934]]


In [40]:
A=np.array([0,12.45,13.8,14.56,15.00])
print(A.max())#mqx and min elements only accepts numeric datatypes int and float
print(A.min())

15.0
0.0


In [44]:
A=np.array([12,13,14,15,12,91,78,90,56,34,50,34]).reshape(3,4)
print(A)
print("--------")
print(A.max(axis=0))#axis-0 coloumnwise max value
print("--------")
print(A.max(axis=1))#axis-1 rowwise max value




[[12 13 14 15]
 [12 91 78 90]
 [56 34 50 34]]
--------
[56 91 78 90]
--------
[15 91 56]


In [45]:
A=np.array([12,13,14,15,12,91,78,90,56,34,50,34]).reshape(3,4)
print(A)
print("--------")
print(A.min(axis=0))#axis-0 coloumnwise min value
print("--------")
print(A.min(axis=1))#axis-1 rowwise min value


[[12 13 14 15]
 [12 91 78 90]
 [56 34 50 34]]
--------
[12 13 14 15]
--------
[12 12 34]


In [ ]:
#joining arrays

In [47]:
#vstack-prints matrices one on other
A=np.array([12,13,14,15]).reshape(2,2)
B=np.array([23,56,78,10]).reshape(2,2)
print(A)
print("----------")
print(B)
print("after vertically stacking the arrays")
print(np.vstack((A,B)))

[[12 13]
 [14 15]]
----------
[[23 56]
 [78 10]]
after vertically stacking the arrays
[[12 13]
 [14 15]
 [23 56]
 [78 10]]


In [48]:
#hstack-prints matrices one side other
A=np.array([12,13,14,15]).reshape(2,2)
B=np.array([23,56,78,10]).reshape(2,2)
print(A)
print("----------")
print(B)
print("after horizontally stacking the arrays")
print(np.hstack((A,B)))

[[12 13]
 [14 15]]
----------
[[23 56]
 [78 10]]
after horizontally stacking the arrays
[[12 13 23 56]
 [14 15 78 10]]


In [52]:
A=np.array([12,13,14,15]).reshape(2,2)
B=np.array([23,56,78,10]).reshape(2,2)
print(A)
print("----------")
print(B)
print("----------")
print(np.stack((A,B),axis=0))

[[12 13]
 [14 15]]
----------
[[23 56]
 [78 10]]
----------
[[[12 13]
  [14 15]]

 [[23 56]
  [78 10]]]


In [53]:
A=np.arange(30).reshape(2,3,5)
print(A)
print("after dstack")
print(np.dstack(A)) #no of rows becomes no of groups
#no of coloumns in every group becomes no of rows in every group


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
after dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [60]:
#splitting arrays!
A=np.arange(18).reshape(6,3)
print(A)
print("after splitting")
(np.vsplit(A,3))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [61]:
A=np.arange(18).reshape(6,3)
print(A)
print("after splitting")
(np.hsplit(A,3))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12],
        [15]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]])]

In [63]:
A=np.arange(18).reshape(6,3)
print(A)
print("after splitting")
(np.vsplit(A,(2,5)))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]),
 array([[15, 16, 17]])]

In [73]:
A=np.arange(18).reshape(3,6)
print(A)
print("after splitting")
(np.hsplit(A,(3)))


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
after splitting


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

In [69]:
A=np.arange(18).reshape(6,3)
print(A)
print("after splitting")
(np.vsplit(A,(2,3)))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [74]:
A=np.arange(18).reshape(3,6)
print(A)
print("after splitting")
(np.hsplit(A,(2,5)))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
after splitting


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10],
        [14, 15, 16]]),
 array([[ 5],
        [11],
        [17]])]

In [76]:
#argmax return the max index element
A=np.array([18,12,90,34,78,67,45,23,45,6,7,5]).reshape(3,4)
print(A)
print(A.argmax(axis=0)) #position[0 0 0 0
                                  1 1 1 1]

[[18 12 90 34]
 [78 67 45 23]
 [45  6  7  5]]
[1 1 0 0]


In [77]:
A=np.array([18,12,90,34,78,67,45,23,45,6,7,5]).reshape(3,4)
print(A)
print(A.argmax(axis=1))#positon [0 1 2 3
                                 0 1 2 3]

[[18 12 90 34]
 [78 67 45 23]
 [45  6  7  5]]
[2 0 0]


In [82]:
A=np.array([18,12,90,34,78,67,45,23,45,6,7,5]).reshape(3,4)
print(A)
print(A.argmin())

[[18 12 90 34]
 [78 67 45 23]
 [45  6  7  5]]
11


In [80]:
A=np.array([18,12,90,34,78,67,45,23,45,6,7,5]).reshape(3,4)
print(A)
print(A.argmin(axis=1))

[[18 12 90 34]
 [78 67 45 23]
 [45  6  7  5]]
[1 3 3]


In [84]:
#numpy statastics !!!with formulas
#mean median mode
A=np.array([12,4,67,78,90])
print("mean is:",np.mean(A))
print("median is:",np.median(A))
print("variance is:",np.var(A))
print("standard deciation is:",np.std(A))


mean is: 50.2
median is: 67.0
variance is: 1246.56
standard deciation is: 35.30665659617178


In [85]:
#trigonometry
A=np.pi#radians
print(A)

3.141592653589793


In [86]:
np.rad2deg(A)#changes from degrees to radians

180.0

In [94]:
A=np.array([np.pi/4,  np.pi/3,  np.pi/2,  np.pi])
print(A)

[0.78539816 1.04719755 1.57079633 3.14159265]


In [95]:
print(np.rad2deg(A))

[ 45.  60.  90. 180.]


In [100]:
C=np.array([0,30,45,60,90,120,180])
D=(np.deg2rad(C))
print(D)

[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]


In [101]:
np.sin(C)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
        0.58061118, -0.80115264])

In [102]:
np.cos(C)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362,
        0.81418097, -0.59846007])

In [103]:
np.tan(C)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
        0.71312301,  1.33869021])

In [107]:
np.arctan(1)

0.7853981633974483

In [108]:
np.arcsin(0)

0.0

In [105]:
np.arcsin(1)

1.5707963267948966

In [106]:
np.arccos(1)

0.0

In [111]:
a=8
b=6
print(np.hypot(a,b))#hypotnuse

10.0


In [113]:
#searching an array
A=np.array([12,34,56,78,90,13,47])
print(np.where(A==78))

(array([3]),)


In [114]:
A=np.array([12,34,56,78,90,13,47])
print(np.where(A%2==0))#even

(array([0, 1, 2, 3, 4]),)


In [115]:
A=np.array([12,34,56,78,90,13,47])
print(np.where(A>25))#greater than 25

(array([1, 2, 3, 4, 6]),)


In [2]:
import numpy as np
A=np.array([12,34,56,78,90,13,47])
B=np.array([45,34,24,35,67,89,90])
print(np.divmod(A,B))

(array([0, 1, 2, 2, 1, 0, 0]), array([12,  0,  8,  8, 23, 13, 47]))


In [3]:
print(np.mod(A,B))

[12  0  8  8 23 13 47]


In [4]:
print(np.diff(A))

[ 22  22  22  12 -77  34]


In [6]:
A=np.array([12,34,56,78,90,13,47])
B=np.array([112,34,56,78,90,23,23])
print(np.diff(A))
print(np.mod(A,B))
print(np.sort(A))

[ 22  22  22  12 -77  34]
[12  0  0  0  0 13  1]
[12 13 34 47 56 78 90]


In [7]:
A=np.array([12,34,56,78,90,13,47])
B=np.array([112,34,56,78,90,23,23])
print(np.setdiff1d(A,B))

[12 13 47]


In [8]:
A=np.array([12,34,56,78,90,13,47])
B=np.array([112,34,56,78,90,23,23])
print(np.intersect1d(A,B))

[34 56 78 90]


In [9]:
A=np.array([12,34,56,78,90,13,47])
B=np.array([112,34,56,78,90,23,23])
print(np.union1d(A,B))

[ 12  13  23  34  47  56  78  90 112]


In [10]:
#rounding
a1=np.fix([1.2345,3.4556])
a2=np.around([1.2345,3.4556])
a3=np.trunc([1.2345,3.4556])
a4=np.floor([1.2345,3.4556])
a5=np.ceil([1.2345,3.4556])
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[1. 3.]
[1. 3.]
[1. 3.]
[1. 3.]
[2. 4.]


In [11]:
A=np.array([12,34,56,78,90,13,47])
print(np.cumsum(A))

[ 12  46 102 180 270 283 330]


In [13]:
A=np.array([12,34,56,78,90,13,47])
print(np.cumprod(A))

[         12         408       22848     1782144   160392960  2085108480
 98000098560]


In [14]:
np.lcm(24,56)

168

In [15]:
np.gcd(24,56)

8

In [17]:
A=np.array([12,45,65,30])
print(np.lcm.reduce(A))

2340


In [19]:
A=np.array([10,45,65,30])
print(np.gcd.reduce(A))

5


In [20]:
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [21]:
#random
from numpy import random as rd

In [24]:
A=rd.rand()#n #default limit 0 to 0.99
print(A)

0.21926580767291337


In [27]:
A=rd.rand(10)#n #default limit 0 to 0.99-10 random numbers
print(A)

[0.67888184 0.58111186 0.4806047  0.52710039 0.82264207 0.58994885
 0.60756286 0.27830857 0.85563594 0.99166525]


In [35]:
A=rd.randint(4)  #randint(limit)==>#limit 0,1,2,3
print(A)

1


In [32]:
A=rd.randint(40,size=6)#limit,size
print(A)

[28  8 34 30 17 38]


In [37]:
A=rd.randint(40,size=(2,3))
print(A)

[[ 3 31 23]
 [32  6 29]]


In [39]:
#joins
A=np.array([1,2,3,4])
B=np.array([5,6,7,8])
#1x5 2x6 3x7
print(np.inner(A,B))

70


In [40]:
A=np.array([1,2,3,4])
B=np.array([5,6,7,8])
#1x5 1x6 1x7
print(np.outer(A,B))

[[ 5  6  7  8]
 [10 12 14 16]
 [15 18 21 24]
 [20 24 28 32]]


In [44]:
A=np.array([1,2,3])
B=np.array([5,6,7])
#det
print(np.cross(A,B))

[-4  8 -4]
