In [ ]:
#variable
a=10
print("i'm",a," years old")

i'm 10  years old


In [ ]:
#arthematic ops on int variables
x=int(input("enter a:"))
y=int(input("enter b:"))
print("sum is:",x+y)
print("difference is:",x-y)
print("product is:",x*y)
print("quotient is:",x/y)
print("remainder is:",x%y)
print("power of x to y is:",x**y)
print("floor div:",x//y)





enter a:25
enter b:35
sum is: 60
difference is: -10
product is: 875
quotient is: 0.7142857142857143
remainder is: 25
power of x to y is: 8470329472543003390683225006796419620513916015625
floor div: 0


In [ ]:
#take salary from user,if salary is more than 50k there is a 10% tax,print his final salary.
x=int(input("enter salary"))
if (x>=50,000):
  b=x*(10/100)
  print("your salary is:",x-b)
else:
  print("no tax")


enter salary60000
your salary is: 54000.0


In [ ]:
#get the salary from user if the salary is more tha or equal to 50k apply 10% tax reduction,
#if salary is less than 50k apply 5%tax,
#if the salary is more than 70k apply 12% tax,
#if salary exceeds 1L print ur promoted to nxt lvl
x=int(input("enter salary:"))
if (x>=50000 and x<70000):
    a=x*(10/100)
    print("your salary is:",x-a)
elif (x<50000):
   b=x*(5/100)
   print("your salary is:",x-b)
elif (x>=70000 and x<100000):
   c=x*(12/100)
   print("your salary is:",x-c)
elif (x>=100000):
   print("your are promoted to next level")

enter salary:0
your salary is: 0.0


In [ ]:
x=int(input("enter num:"))
for i in range (1,x):
  print(i)

enter num:5
1
2
3
4


In [ ]:
x=int(input("enter num:"))
for i in range(1,11):
  print(x,"*",i,"=",i*x)

enter num:15
15 * 1 = 15
15 * 2 = 30
15 * 3 = 45
15 * 4 = 60
15 * 5 = 75
15 * 6 = 90
15 * 7 = 105
15 * 8 = 120
15 * 9 = 135
15 * 10 = 150


In [ ]:
x=int(input("enter num"))
i=1
while(i<=10):
  print(x,"*",i,"=",i*x)
  i=i+1



enter num15
15 * 1 = 15
15 * 2 = 30
15 * 3 = 45
15 * 4 = 60
15 * 5 = 75
15 * 6 = 90
15 * 7 = 105
15 * 8 = 120
15 * 9 = 135
15 * 10 = 150


In [ ]:
#list:heterogenous
l1=[1,'uma','abc',2.8]
l1.append('sri')#listname.append(ele)
print(l1)

[1, 'uma', 'abc', 2.8, 'sri']


In [ ]:
l1=[1,'uma','abc',2.8]
l1.insert(2,"hie")#listname.insert(index,ele)
print(l1)

[1, 'uma', 'hie', 'abc', 2.8]


In [ ]:
l1=[1,'uma','abc',2.8]
l2=['anu','rohini']
l=l1+l2
print(l)

[1, 'uma', 'abc', 2.8, 'anu', 'rohini']


In [ ]:
l1=[1,'uma','abc',2.8]
l1.pop(3)#listname.pop(index)
print(l1)

[1, 'uma', 'abc']


In [ ]:
l1=[1,'uma','abc',2.8]
l1.remove('abc')#listname.remove(ele)
print(l1)

[1, 'uma', 2.8]


In [ ]:
l1=[1,'uma','abc',2.8]
l1.clear()#listname.clear()
print(l1)

[]


In [ ]:
#create a list of 10 integer elements print their squares and save in a new list
l=[10,20,30,40,50,60,70,80,90,100]
l1=[i*i for i in l]
print(l1)


[100, 400, 900, 1600, 2500, 3600, 4900, 6400, 8100, 10000]


In [ ]:
l=[10,20,30,40,50,60,70,80,90,100]
l1=[i*i for i in l if i>50]
print(l1)


[3600, 4900, 6400, 8100, 10000]


In [2]:
#new list=[(st of if)if (cond) else (st of else) for]
l1=[10,20,30,40,50,60,70,80,90,100]
l=[i*i if i>50 else 'X' for i in l1]
print(l)

['X', 'X', 'X', 'X', 'X', 3600, 4900, 6400, 8100, 10000]


In [11]:
#take the salary from user if salary is less than 50k 10% tax otherwise 15%tax
x=[20000,56000,60000,45000]
l=[i-i*(10/100) if i<50000 else i-i*(15/100) for i in x]
print(l)

[18000.0, 47600.0, 51000.0, 40500.0]


In [16]:
#create dict
dict1={"mentor":'jwalitha',28:'uma',22:'anu',1:'rohini'}
print(dict1.keys())
print(dict1.values())
print(dict1[28])

dict_keys(['mentor', 28, 22, 1])
dict_values(['jwalitha', 'uma', 'anu', 'rohini'])
uma


In [23]:
d={"dept":"cse","details":{"year":2,"section":"d","count":71}}
print("year is",d["details"]["year"] )
print("section is",d["details"]["section"] )


year is 2
section is d


In [34]:
l1=[1,2,3,4]
l2=['rohini','anu','uma','sri']
new_zip=(zip(l1,l2))
for i in new_zip:
  print(i)

(1, 'rohini')
(2, 'anu')
(3, 'uma')
(4, 'sri')


In [ ]:
l1=[1,2,3,4]
l2=['rohini','anu','uma','sri']
new=dict(zip(l1,l2))
print(new)

In [51]:
import numpy as np
A=np.array([1,2,3,4])#1d
print(A.ndim)
print(A.shape)

1
(4,)


In [55]:
import numpy as np
A=np.array([[1,2],[2,3],[3,4],[4,5]])
#ele in each row =columns
print(A.ndim)
print(A.shape)
print(A)

2
(4, 2)
[[1 2]
 [2 3]
 [3 4]
 [4 5]]


In [59]:
import numpy as np
A=np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
#ele in each row =columns
print(A.ndim)
print(A.shape)
print(A)

3
(2, 2, 4)
[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [62]:
A=np.zeros((2,2,3))#grps,rows,col
print(A)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [63]:
A=np.eye(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [66]:
A=np.arange(1,10,2)#start,stop,step
print(A)
print(type(A))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [71]:
#print all the numbers that are divisible by 8 using arange fun b/w 1&1000
A=np.arange(8,1001,8)
print(A)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [73]:
#slippting arange into n numbers with common differences
A=np.linspace(48,50,10)
print(A)

[48.         48.22222222 48.44444444 48.66666667 48.88888889 49.11111111
 49.33333333 49.55555556 49.77777778 50.        ]
